spring:
  datasource:
    url: jdbc:h2:mem:taskdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
    initialization-mode: always
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  sql:
    init:
      platform: h2
    mode: always



